#!/usr/bin/env python

__appname__ = 'duplicates.py'
__author__  = 'Jeremy Cantrell <jmcantrell@gmail.com>'
__url__     = 'http://jmcantrell.me'
__date__    = 'Mon 2010-10-18 23:25:54 (-0400)'
__license__ = 'BSD'

import os, hashlib
from scriptutils.arguments import Arguments

def md5sum(fn):
    md5 = hashlib.md5()
    f = open(fn, 'rb')
    while True:
        data = f.read(128)
        if not data: break
        md5.update(data)
    return md5.hexdigest()

def get_arguments():
    a = Arguments(description="Finds duplicate files.")
    a.add_argument('-d', '--directory', default='.', help='Search DIRECTORY for duplicates.')
    return a.parse_args()

def main():
    args = get_arguments()
    hashes = {}
    for root, dirs, files in os.walk(os.path.expanduser(args.directory)):
        for f in files:
            fn = os.path.join(root, f)
            hashes.setdefault(md5sum(fn), []).append(fn)
    for k, v in hashes.items():
        if len(v) > 1:
            print '%s: %s' % (k, ', '.join(v))


if __name__ == '__main__': main()
