#!/usr/bin/env bash

# Filename:      gnome-terminal
# Description:   Hack for truly getting rid of gnome-terminal.
# Maintainer:    Jeremy Cantrell <jmcantrell@gmail.com>
# Last Modified: Sun 2010-10-03 02:59:39 (-0400)

# There are way too many projects out there that hardcode 'gnome-terminal'
# when they should be using 'x-terminal-emulator'. This annoys the shit out of
# me and this is the answer to it. It provides a drop-in replacement for
# gnome-terminal and executes the right command instead.

ARGS=()

for arg in "$@"; do
    [[ $arg == -e ]] && arg=-x
    ARGS=("${ARGS[@]}" "$arg")
done

xterm "${ARGS[@]}"
