#!/usr/bin/env python

"""Get the GnomeVFS URI from a path."""

__appname__ = 'gnomevfs-uri.py'
__author__  = 'Jeremy Cantrell <jmcantrell@gmail.com>'
__url__     = 'http://jmcantrell.me'
__date__    = 'Mon 2010-10-18 23:19:34 (-0400)'
__license__ = 'BSD'

import gnomevfs
from scriptutils.arguments import Arguments

def get_arguments(): #{{{1
    a = Arguments(description="Get the GnomeVFS URI from a path.")
    a.add_argument('paths', nargs='+', metavar='PATH', help='a path to translate')
    return a.parse_args()

def main(): #{{{1
    args = get_arguments()
    for p in args.paths:
        try:
            print gnomevfs.get_uri_from_local_path(p)
        except RuntimeError:
            print p

#}}}1

if __name__ == '__main__': main()
