#!/usr/bin/env python

"""Get the path from a GnomeVFS URI."""

__appname__ = 'gnomevfs-path.py'
__author__  = 'Jeremy Cantrell <jmcantrell@gmail.com>'
__url__     = 'http://jmcantrell.me'
__date__    = 'Mon 2010-10-18 23:23:34 (-0400)'
__license__ = 'BSD'

import gnomevfs
from scriptutils.arguments import Arguments

def get_arguments(): #{{{1
    a = Arguments(description="Get the path from a GnomeVFS URI.")
    a.add_argument('paths', nargs='+', metavar='PATH', 'a path to translate')
    return a.parse_args()

def main(): #{{{1
    args = get_arguments()
    for p in args.paths:
        try:
            print gnomevfs.get_local_path_from_uri(p)
        except RuntimeError:
            print p

#}}}1

if __name__ == '__main__': main()
