#!/usr/bin/env python

"""Get the GnomeVFS URI from a path."""

__appname__ = 'gnomevfs-uri.py'
__author__  = 'Jeremy Cantrell <jmcantrell@gmail.com>'
__url__     = 'http://jmcantrell.me'
__date__    = 'Fri 2010-04-23 13:05:22 (-0400)'
__license__ = 'BSD'

import gnomevfs
from scriptutils.options import Options

def get_options(): #{{{1
    return Options(args='[path...]').parse_args()

def main(): #{{{1
    opts, args = get_options()
    for arg in args:
        try:
            print gnomevfs.get_uri_from_local_path(arg)
        except RuntimeError:
            print arg

#}}}1

if __name__ == '__main__': main()
