#!/usr/bin/env bash

# Filename:      mangrep
# Description:   Grep man pages.
# Maintainer:    Jeremy Cantrell <jmcantrell@gmail.com>
# Last Modified: Sun 2010-10-03 02:59:24 (-0400)

OIFS=$IFS; IFS=:
for dir in $(manpath -g); do
    IFS=$OIFS
    [[ -d $dir ]] && find "$dir" -type f -exec zgrep -l "$@" {} \;
done
