#!/usr/bin/env bash

# Filename:      python-init.sh
# Description:   Setup system with essential python tools.
# Maintainer:    Jeremy Cantrell <jmcantrell@gmail.com>
# Last Modified: Tue 2010-09-14 20:45:18 (-0400)

source bashful-files

OPWD=$PWD

tempfile -d; cd "$TEMPFILE"

curl -O http://python-distribute.org/distribute_setup.py
python distribute_setup.py

easy_install -U pip==dev

mkdir -p "$(python-directory -p $HOME/.local)"

packages=(
    dateutils
    igrep
    imageutils
    mimemail
    pathtags
    pathutils
    scriptutils
    unicodeutils
    virtualenv
    virtualenvwrapper
    )

for package in "${packages[@]}"; do
    pip install -U --user "$package"
done

pip install -U --user -r ~/.virtualenvs/requirements/base

cd "$OPWD"
