#!/usr/bin/env bash

# Filename:      python-select.sh
# Description:   Chooses a version of python from the installed frameworks.
# Maintainer:    Jeremy Cantrell <jmcantrell@gmail.com>
# Last Modified: Tue 2010-09-14 23:35:37 (-0400)

source bashful-messages
source bashful-modes

SCRIPT_NAME=$(basename "$0" .sh)
SCRIPT_ARGS="[VERSION]"
SCRIPT_USAGE="Chooses a version of python from the installed frameworks."

[[ $(uname) == Darwin ]] || die "This script is designed to only work on OS X."

unset OPTIND
while getopts ":h" option; do
    case $option in
        h) usage 0 ;;
        *) usage 1 ;;
    esac
done && shift $(($OPTIND - 1))

VERSION=$1

SYSDIR=/Library/Frameworks/Python.framework/Versions
LOCDIR=$HOME/Library/Python

if [[ -z $VERSION ]]; then
    find "$SYSDIR" -maxdepth 1 -mindepth 1 -type d -name "[0-9]*" | sort | xargs basename
    exit
fi

cd "$SYSDIR"

sudo ln -sfn "$VERSION" Current

mkdir -p "$LOCDIR/$VERSION"

cd "$LOCDIR"

ln -sfn "$VERSION" Current
