#!/usr/bin/env python

"""URL encodes key-value pairs."""

__author__  = 'Jeremy Cantrell <jmcantrell@gmail.com>'
__url__     = 'http://jmcantrell.me'
__date__    = 'Fri 2010-04-23 13:05:13 (-0400)'
__license__ = 'BSD'

import sys, urllib
from itertools import chain, repeat, izip
from scriptutils.options import Options

def grouper(n, itr, pad=None): #{{{1
    return izip(*[chain(itr, repeat(pad, n-1))]*n)

def get_options(): #{{{1
    return Options(args='[key value...]').parse_args()

def main(): #{{{1
    opts, args = get_options()
    print urllib.urlencode(dict(grouper(2, sys.argv[1:])))

#}}}1

if __name__ == '__main__': main()
