#!/usr/bin/env python

"""URL encodes key-value pairs."""

__author__  = 'Jeremy Cantrell <jmcantrell@gmail.com>'
__url__     = 'http://jmcantrell.me'
__date__    = 'Mon 2010-10-18 23:16:35 (-0400)'
__license__ = 'BSD'

import sys, urllib
from itertools import chain, repeat, izip
from scriptutils.arguments import Arguments

def grouper(n, itr, pad=None): #{{{1
    return izip(*[chain(itr, repeat(pad, n-1))]*n)

def get_arguments(): #{{{1
    a = Arguments(description="URL encodes key-value pairs.")
    a.add_argument('key_values', nargs='+', metavar='KEY-VALUE', help='a key and value pair to encode')
    return a.parse_args()

def main(): #{{{1
    args = get_arguments()
    print urllib.urlencode(dict(grouper(2, args.key_values)))

#}}}1

if __name__ == '__main__': main()
