#!/usr/bin/env python

"""Utility for working with version strings."""

__author__  = 'Jeremy Cantrell <jmcantrell@gmail.com>'
__url__     = 'http://jmcantrell.me'
__date__    = 'Fri 2010-04-23 13:05:33 (-0400)'
__license__ = 'BSD'

import os, sys
from scriptutils.options import Options

def split_version(version): #{{{1
    return list(int(i) for i in version.split('.'))

def join_version(version): #{{{1
    return '.'.join([str(i) for i in version])

def increment_version(version, idx): #{{{1
    for i in range(len(version), idx+1):
        version.append(0)
    version[idx] += 1
    for i in range(idx+1, len(version)):
        version[i] = 0
    return version

def get_options(): #{{{1
    opts = Options(args='[version...]')
    opts.add_option('-M', '--major',   action='store_true', help='Add to major version.')
    opts.add_option('-m', '--minor',   action='store_true', help='Add to minor version.')
    opts.add_option('-b', '--build',   action='store_true', help='Add to build version.')
    opts.add_option('-s', '--sort',    action='store_true', help='Sort.')
    opts.add_option('-r', '--reverse', action='store_true', help='Reverse order.')
    return opts.parse_args()

def main(): #{{{1
    opts, args = get_options()

    if len(args):
        versions = args
    else:
        versions = sys.stdin.readlines()

    versions = [split_version(v) for v in versions]

    if opts.build: versions = [increment_version(v, 2) for v in versions]
    if opts.minor: versions = [increment_version(v, 1) for v in versions]
    if opts.major: versions = [increment_version(v, 0) for v in versions]

    if opts.sort:    versions.sort()
    if opts.reverse: versions.reverse()

    versions = [join_version(v) for v in versions]

    print os.linesep.join(versions)

#}}}1

if __name__ == '__main__': main()
